on: push
name: 🚀 Deploy API on push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SSH and run commands
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Coloque sua chave SSH privada como secret
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "$SSH_PRIVATE_KEY") ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }} "cd ${{ secrets.PROJECT_PATH }} && git pull && composer update && composer dump-autoload"
